In [3]:
import numpy as np


In [2]:
testData = [[149, 433, 0],
 [174, 424, -15],
 [194, 397, -18],
 [182, 365, -19],
 [169, 347, -20],
 [212, 374, -4],
 [240, 351, -9],
 [255, 339, -14],
 [269, 327, -18],
 [197, 362, -3],
 [221, 334, -6],
 [235, 317, -10],
 [247, 302, -13],
 [180, 358, -4],
 [195, 329, -12],
 [207, 312, -19],
 [217, 296, -24],
 [160, 361, -7],
 [167, 341, -16],
 [166, 350, -17],
 [163, 360, -17]]

In [3]:

def flatten():
    return np.array([each for sublist in testData for each in sublist])

def flatten2():
    return np.array(testData).flatten()

import itertools
def flatten3():
    return np.array(list(itertools.chain.from_iterable(testData)))

def flatten4():
    return np.fromiter(itertools.chain.from_iterable(testData), int)

def flatten5():
    return np.concatenate(testData)

import timeit
print(timeit.timeit(flatten , number=100000))
print(timeit.timeit(flatten2, number=100000))
print(timeit.timeit(flatten3, number=100000))
print(timeit.timeit(flatten4, number=100000))
print(timeit.timeit(flatten5, number=100000))

1.0394668
1.5088916999999995
0.6989552000000003
0.420871
2.276574000000001


NP Difference

In [26]:
x1 = np.random.rand(100)
x2 = np.random.rand(100)


def f1():
    return x1-x2


def f2():
    return np.subtract(x1, x2)

import timeit
print(timeit.timeit(f1, number=100000))
print(timeit.timeit(f2, number=100000))

0.07274620000004006
0.07178519999996524


In [24]:
np.random.rand(10)

array([0.479057  , 0.40316443, 0.20395125, 0.27706597, 0.27883321,
       0.95923075, 0.54442159, 0.41625724, 0.07260183, 0.64543261])

In [16]:
test = {'lmList': [[916, 488, 0], [890, 467, -8], [858, 452, -15], [833, 438, -20], [821, 420, -27], [844, 487, -25], [814, 479, -34], [795, 470, -38], [781, 462, -41], [849, 512, -25], [819, 526, -33], [801, 536, -37], [789, 546, -41], [859, 531, -25], [837, 554, -33], [823, 569, -39], [813, 583, -43], [872, 542, -25], [858, 568, -33], [851, 584, -38], [845, 599, -41]], 'bbox': (781, 420, 135, 179), 'center': (848, 509), 'type': 'Left'}
test

{'lmList': [[916, 488, 0],
  [890, 467, -8],
  [858, 452, -15],
  [833, 438, -20],
  [821, 420, -27],
  [844, 487, -25],
  [814, 479, -34],
  [795, 470, -38],
  [781, 462, -41],
  [849, 512, -25],
  [819, 526, -33],
  [801, 536, -37],
  [789, 546, -41],
  [859, 531, -25],
  [837, 554, -33],
  [823, 569, -39],
  [813, 583, -43],
  [872, 542, -25],
  [858, 568, -33],
  [851, 584, -38],
  [845, 599, -41]],
 'bbox': (781, 420, 135, 179),
 'center': (848, 509),
 'type': 'Left'}

In [23]:

from itertools import chain
# Flatten a 2d np array into 1d array
def flatten2dList(arr, dataType=int):
    return np.fromiter(chain.from_iterable(arr), dataType)

    # Get the largest absolute value in an np array
def getAbsLargestVal(arr):
    return max(np.max(arr), abs(np.min(arr)))
    

In [68]:
# Offset and normalize the landmark list
def preprocess_landmarks(landmark_list):
    if not landmark_list:
        return []
    
    # Offset every point with respect to the first point
    new_landmark_list = []
    origin_x = landmark_list[0][0] 
    origin_y = landmark_list[0][1]
    origin_z = landmark_list[0][2]
    for each in landmark_list:
        updated_point = [
            each[0] - origin_x, 
            each[1] - origin_y, 
            each[2] - origin_z
        ]
        new_landmark_list.append(updated_point)
    
    # Convert to 1D-array
    new_landmark_list = flatten2dList(new_landmark_list)
    
    # Get highest absolute value
    largest_value = getAbsLargestVal(new_landmark_list)
    
    # Normalization
    return new_landmark_list / largest_value

In [76]:
# Offset and normalize the landmark list
def preprocess_landmarks2(landmark_list):
    if not landmark_list:
        return []

    landmark_list = np.array(landmark_list, dtype=float)
    origin = landmark_list[0]

    new_landmark_list = (landmark_list - origin).ravel()
    
    # # Offset every point with respect to the first point
    
    # # Convert to 1D-array
    
    # # Get highest absolute value
    largest_value = getAbsLargestVal(new_landmark_list)
    
    # Normalization
    return new_landmark_list / largest_value

In [71]:
# Offset and normalize the landmark list
def preprocess_landmarks3(landmark_list):
    if not landmark_list:
        return []

    landmark_list = np.array(landmark_list, dtype=float)
    origin = landmark_list[0]

    new_landmark_list = landmark_list - origin
    
    # # Offset every point with respect to the first point
    
    # # Convert to 1D-array
    new_landmark_list = new_landmark_list.flatten()
    
    # # Get highest absolute value
    largest_value = getAbsLargestVal(new_landmark_list)
    
    # Normalization
    return new_landmark_list / largest_value

In [77]:
print(preprocess_landmarks(test['lmList']))
print(preprocess_landmarks2(test['lmList']))
print(preprocess_landmarks(test['lmList']) == preprocess_landmarks2(test['lmList']))

[ 0.          0.          0.         -0.19259259 -0.15555556 -0.05925926
 -0.42962963 -0.26666667 -0.11111111 -0.61481481 -0.37037037 -0.14814815
 -0.7037037  -0.5037037  -0.2        -0.53333333 -0.00740741 -0.18518519
 -0.75555556 -0.06666667 -0.25185185 -0.8962963  -0.13333333 -0.28148148
 -1.         -0.19259259 -0.3037037  -0.4962963   0.17777778 -0.18518519
 -0.71851852  0.28148148 -0.24444444 -0.85185185  0.35555556 -0.27407407
 -0.94074074  0.42962963 -0.3037037  -0.42222222  0.31851852 -0.18518519
 -0.58518519  0.48888889 -0.24444444 -0.68888889  0.6        -0.28888889
 -0.76296296  0.7037037  -0.31851852 -0.32592593  0.4        -0.18518519
 -0.42962963  0.59259259 -0.24444444 -0.48148148  0.71111111 -0.28148148
 -0.52592593  0.82222222 -0.3037037 ]
[ 0.          0.          0.         -0.19259259 -0.15555556 -0.05925926
 -0.42962963 -0.26666667 -0.11111111 -0.61481481 -0.37037037 -0.14814815
 -0.7037037  -0.5037037  -0.2        -0.53333333 -0.00740741 -0.18518519
 -0.75555556 

In [72]:

def f1():
    preprocess_landmarks(test['lmList'])
def f2():
    preprocess_landmarks2(test['lmList'])
def f3():
    preprocess_landmarks3(test['lmList'])

import timeit
print(timeit.timeit(f1, number=100000))
print(timeit.timeit(f2, number=100000))
print(timeit.timeit(f3, number=100000))

5.713227800000141
3.9231790000001183
4.172588500000074


In [75]:

def getAbsLargestVal1(arr):
    return max(np.max(arr), abs(np.min(arr)))
def getAbsLargestVal2(arr):
    return np.max(np.abs(arr))

g = np.random.rand(1000)
    
print(timeit.timeit(lambda: getAbsLargestVal2(g), number=100000))
print(timeit.timeit(lambda: getAbsLargestVal1(g), number=100000))

1.4366385999996965
2.1783331999999973


# Appending List

In [114]:
import itertools, sys
def appList1():
    final = []
    print(sys.getsizeof(final))
    for training in range(100):
        temp = []
        for frame_num in range(15):
            temp.append(np.random.rand(248))
        final.append(temp)
    print(sys.getsizeof(final))
    print(sys.getsizeof(np.array(final)))
    return np.array(final)

def appList2():
    final = []
    for training in range(100):
        temp = []
        for frame_num in range(15):
            temp.append(np.random.rand(248))
        final.append(np.fromiter(itertools.chain.from_iterable(temp), float))
    return np.array(final)


def appList3():
    final = np.zeros((100, 15, 248))
    print(sys.getsizeof(final))
    for training in range(100):
        for frame_num in range(15):
            final[training][frame_num] = (np.random.rand(248))
    print(sys.getsizeof(final))
    return final

In [118]:
appList3()

2976144
2976144


array([[[0.24595914, 0.47634274, 0.64822444, ..., 0.02679062,
         0.25990268, 0.60965637],
        [0.81980773, 0.05908029, 0.55602314, ..., 0.48338785,
         0.95140049, 0.63550204],
        [0.32433949, 0.22527092, 0.83481985, ..., 0.29875144,
         0.03227199, 0.01464374],
        ...,
        [0.44244997, 0.50426324, 0.22999833, ..., 0.28923081,
         0.41876257, 0.50327589],
        [0.13648631, 0.43896356, 0.45883598, ..., 0.93893916,
         0.73919185, 0.13629719],
        [0.05161625, 0.34770991, 0.84599388, ..., 0.79202084,
         0.04390037, 0.63479622]],

       [[0.53988354, 0.27463844, 0.3947502 , ..., 0.32783493,
         0.79430079, 0.82208954],
        [0.08598853, 0.35736607, 0.24512028, ..., 0.06244166,
         0.16823852, 0.91469721],
        [0.78898611, 0.55710069, 0.43324516, ..., 0.21554692,
         0.08444185, 0.40153495],
        ...,
        [0.5575474 , 0.94186418, 0.30761443, ..., 0.7347195 ,
         0.78317055, 0.93258347],
        [0.8

In [109]:

# print(timeit.timeit(lambda: appList2(), number=100))
print(timeit.timeit(lambda: appList3(), number=100))
print(timeit.timeit(lambda: appList1(), number=100))

0.7966308000004574
0.8055443000002924


In [7]:
import numpy as np
import timeit

In [8]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = np.array([1, 2, 3])

def f1():
    return np.concatenate((a, b, c))

def f2():
    return np.hstack((a, b, c))

f2()

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [12]:

# print(timeit.timeit(lambda: appList2(), number=100))
print(timeit.timeit(lambda: f2(), number=10000))
print(timeit.timeit(lambda: f1(), number=10000))

0.059487499999704596
0.024055200000020704
